repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        exclude: ^tests/reference_files*
    -   id: trailing-whitespace
        exclude: ^tests/reference_files*
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black
        exclude: ^docs/
