# This file is the user configuration file, edit it to your needs!

import:
    single file import: No      # No: select folders containing files
    labjournal available: Yes
    ask for labjournal: Yes     # No: will look in parent folder
    fallback method: Image      # if not specified in labjournal e.g. ecstm, stm, afm, cv, raman, image
    allowed file types: 
      - txt                     # Renishaw Raman files
      - SM4                     # RHK STM/ECSTM files
      - nid                     # Nanosurf STM/AFM files
      - lvm                     # Labview files
      - bmp                     # image
      - png                     # image
      - dat                     # E20 XPS files
      - mpt                     # Biologic Potentiostat (CV, PEIS, Chrono)
      - tif                     # SEM / SPM
      - csv                     # PHI XPS files
      - gwy                     # Park AFM files
      - mul                     # Specs STM files
    labjournal worksheet name: overview
    initial directory prompt labjournal: G:\Surface-Microscopy\SM-ECSTM\Data\1_labjournals
    initial directory prompt files: G:\Surface-Microscopy\SM-ECSTM\Data


spm:    
    # Functions and parameters to run on the spm data
    immediate functions:
        - level
        - align_rows
        - fix_zero
    
    # Use "view log" within Gwyddion for parameters:
    align rows:
        max degree: 3
        do extract: No
        do plot: No
        method: 0
        masking: 2
    
    median background:
        radius: 9
        do extract: No
    
    rotate:
        angle: 0
        create mask: No
        interp: 2
        resize: 1
        show grid: No
    
    scale:
        interp: 2
        proportional: 1
        aspectratio: 1
    
    asciiexport:
        add comment: Yes


export:
    create html report: Yes 
    image export modification dialog: No
    server path: file://///nas.ads.mwn.de/tuch/pc1/Surface-Microscopy/SM-ECSTM    # Create overlap with source directory
    move html to parent and rest in subfolder: Yes
    Force overwrite excisting files: Yes
    export data type: txt
    export igor friendly: Yes   #tb0 etc
    export image type: png
    log level: 10    # 0 (minimal info) ... 10 (print everything)
    log file name: _processing.log


system:
    win32 gwy name: gwyddion.exe
    win32 gwy path hint: C:\Program Files (x86)\Gwyddion\bin
    win32 gwyutils rel path: share\gwyddion\pygwy
    linux gwyutils path: /usr/share/gwyddion/pygwy
    debug modus: No

